# https://docs.streamlit.io/library/advanced-features/configuration

[theme]
base="dark"
primaryColor="#2D55F7"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#F0F2F6"
textColor="#262730"
font="sans serif"

[server]
port = 8501

[browser]
gatherUsageStats = false